### Q. 남녀 파트너 정해주기 프로그램(zip) 
같은 수의 남녀 모임에서 파트너를 랜덤하게 정해주는 프로그램을 만들어 보세요

male = ['철수','갑돌','로미오','이몽룡','온돌']

female = ['미미','갑순','줄리엣','성춘향','평강']


In [28]:
import random 
import numpy as np

male = ['철수','갑돌','로미오','이몽룡','온돌']
female = ['미미','갑순','줄리엣','성춘향','평강']

print("파트너 정해드립니다""\n")

for i in range(5):
    a = np.random.choice(male,1)
    b = np.random.choice(female,1)
    print(f'{a} ❤︎ {b}')
    
    male.remove(a)
    female.remove(b)


    

파트너 정해드립니다

['온돌'] ❤︎ ['줄리엣']
['갑돌'] ❤︎ ['미미']
['이몽룡'] ❤︎ ['성춘향']
['로미오'] ❤︎ ['평강']
['철수'] ❤︎ ['갑순']


In [29]:
male = ['철수','갑돌','로미오','이몽룡','온돌']
female = ['미미','갑순','줄리엣','성춘향','평강']

random.shuffle(male)
print(male)
random.shuffle(female)
print(female)

couples = zip(male,female)
for i, couple in enumerate(couples):
    print(f'커플 {i+1}: {couple[0]},{couple[1]}')

['철수', '로미오', '온돌', '이몽룡', '갑돌']
['성춘향', '미미', '평강', '갑순', '줄리엣']
커플 1: 철수,성춘향
커플 2: 로미오,미미
커플 3: 온돌,평강
커플 4: 이몽룡,갑순
커플 5: 갑돌,줄리엣


#### Q2. 사용자가 입력한 횟수만큼 로또 번호를 출력하는 프로그램을 작성하세요.(중복 금지)

[도전과제] 발표자를 원하는 수 만큼 랜덤하게 출력하는 프로그램을 작성하세요.

In [ ]:
list = ['변서연', '한지웅', '양주희', '이호원','정지은','이정현A','이명진','이상윤','조승현',
        '강유한','김영선','최애림','김민섭','박혜린','이정현B','윤정준','김진형','정승기',
       '진청아','신창훈','김병석','박세희']


In [6]:
import random 
import numpy as np


list = ['박영권','김현지','김덕현','변서연','한지웅','양주희','이호원','정지은','이정현A',
         '이정현B','이명진','이상윤','조승현','강유한','김영선','최애림','김민섭','박혜린',
         '윤정준','김진형','진청아','신창훈','김병석','박세희']



print("=============== CAKD7 발표자 랜덤 뽑기 입니다.==============="'\n')
                        
get_ran_num = int(input(" 발표 인원을 입력해주세요 >  "'\n')) 


lucky_guy = random.sample(list,get_ran_num)

print(" ")
for i in range(get_ran_num):
    print(f'{i+1}번 문제 발표자는 {lucky_guy[i]} 입니다.')




=============== CAKD7 발표자 랜덤 뽑기 입니다.===============

 발표 인원을 입력해주세요 >  
10
 
1번 문제 발표자는 진청아 입니다.
2번 문제 발표자는 이정현B 입니다.
3번 문제 발표자는 박세희 입니다.
4번 문제 발표자는 양주희 입니다.
5번 문제 발표자는 최애림 입니다.
6번 문제 발표자는 이명진 입니다.
7번 문제 발표자는 강유한 입니다.
8번 문제 발표자는 김병석 입니다.
9번 문제 발표자는 김민섭 입니다.
10번 문제 발표자는 김덕현 입니다.


#### Q.사용자가 입력한 횟수만큼 로또 번호를 출력하는 프로그램을 작성하세요.(중복 금지)

In [9]:
import random

user = int(input('로또를 시행할 횟수를 입력해주세요'))

i=0

while i < user:
    lotto = list(range(1,46))
    print(random.sample(lotto,6))
    i += 1

로또를 시행할 횟수를 입력해주세요4
[6, 27, 23, 38, 41, 37]
[42, 32, 34, 23, 15, 4]
[45, 12, 29, 44, 2, 33]
[29, 41, 17, 7, 27, 6]


#### Q3.입력받은 문자열의 각 문자를 그 다음 문자로 변경하여 출력하세요. abc->bca

In [8]:
import numpy as np

text = input('텍스트를 입력하세요 >')
ret = ''
for i in range(len(text)):
    if i != len(text)-1:
        ret += text[i+1]
    else:
        ret += text[0]
print(ret)
        
# 다른 방법
# word = input('텍스트를 입력하세요 >')
# print(word[1:]+word[0])

텍스트를 입력하세요 >vvhj
vhjv


In [10]:
# news.naver.com 추출

import re

url = 'https://news.naver.com/mnews/article/057/0001676870?sid=102'
tmp = url.split('/')
tmp[2]

'news.naver.com'

#### Q5. URL 에서 쿼리문을 추출하여 출력하세요.

In [40]:
# url에서 '?'뒤에 표시되는 문자열을 쿼리 문자열이라고 하며 변수=값 사이 &로 
# 구분되어 나열된다. ex) mode=LSD mid=shm
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'
tmp = url.split('?')
a = tmp[1].split('&')
a

['mode=LSD', 'mid=shm', 'sid1=105', 'oid=028', 'aid=0002334601']

#### Q6. 텍스트 파일(mydata.txt)을 읽고  파일의 내용에서 나타나는 문자들에 대해 자주 나타나는 문자들을 아래와 같이 순서대로 출력하세요.
- \[ \] 백슬래시-> [177]회 나타남
- [e] -> [97]회 나타남
- [t] -> [85]회 나타남


In [42]:
import pandas as pd
import string

def getTextFreq(filename):
    with open(filename,'r') as f:
        text = f.read()
        fa = {}
        for c in text:
            if c in fa:
                fa[c] += 1 
            else:
                fa[c] = 1 # 처음 나오면 카운트 : 1
    return fa
ret = getTextFreq('./mydata.txt')
ret = sorted(ret.items(),key=lambda x:x[1], reverse=True)
print(ret)
for c, freq in ret:
    if c =='\n':
        continue
    print('[%c] - > [%d]회 나타남' %(c,freq))



[(' ', 177), ('e', 97), ('t', 85), ('a', 78), ('o', 73), ('n', 60), ('s', 60), ('r', 54), ('i', 50), ('h', 48), ('\n', 43), ('l', 34), ('u', 27), ('d', 24), ('c', 23), ('w', 20), ('m', 20), ('f', 17), ('y', 15), ('p', 15), ('b', 13), ('g', 11), ('v', 9), ("'", 8), ('k', 7), ('!', 2)]
[ ] - > [177]회 나타남
[e] - > [97]회 나타남
[t] - > [85]회 나타남
[a] - > [78]회 나타남
[o] - > [73]회 나타남
[n] - > [60]회 나타남
[s] - > [60]회 나타남
[r] - > [54]회 나타남
[i] - > [50]회 나타남
[h] - > [48]회 나타남
[l] - > [34]회 나타남
[u] - > [27]회 나타남
[d] - > [24]회 나타남
[c] - > [23]회 나타남
[w] - > [20]회 나타남
[m] - > [20]회 나타남
[f] - > [17]회 나타남
[y] - > [15]회 나타남
[p] - > [15]회 나타남
[b] - > [13]회 나타남
[g] - > [11]회 나타남
[v] - > [9]회 나타남
['] - > [8]회 나타남
[k] - > [7]회 나타남
[!] - > [2]회 나타남


#### Q7. 두 개의 수를 입력한 후 두 개의 수에 대한 사칙연산을 수행하세요.(0을 입력한 경우 다시 입력하도록 조치)
- Cal4클래스를 만들어서 작성

#### Q8. Order 클래스를 상속받아 extraOrder 클래스에서 메소드 오버라이딩하여 출력 가격에 '원'이 추가되도록 출력하세요.

In [7]:
class Order: 
    def __init__(self, name): 
        self.customer = 0 
        self.name = name 
    def order(self, price): 
        self.customer += price 
        return self.customer

order = Order('kevin')
print(order.order(1000))

1000


In [15]:
class extraOrder(Order):
    def __init__(self, name):
        super().__init__(name)
        
    def order(self, price): 
        super().order(price)
        print(f'{self.name}님의 주문금액은 {self.customer}원 입니다.')
    
extraorder = extraOrder('kevin')
extraorder.order(1000)

kevin님의 주문금액은 1000원 입니다.


#### Q9. 업무 미팅이 2시임을 알려주는 자동 이메일을 클래스 AutoEmail을 작성하여 아래와 같이 출력하세요.

안녕하세요. Kevin님, 업무미팅은 2시입니다.

In [17]:
import time
class AutoEmail:
    def __init__(self,name,t):
        self.name = name
        self.t = t
    def alarm(self):
        if time.localtime().tm_hour == self.t:
            print(f'{self.name}님, 업무미팅이 진행중입니다.')
        else:
            print(f'안녕하세요 {self.name}님, 업무미팅은 {self.t}시 입니다.')
            
ae = AutoEmail('고갱',9)
ae.alarm()

고갱님, 업무미팅이 진행중입니다.


#### Q10.정규표현식을 사용하여 text에서 전화번호만 출력하세요.
text = "문의사항이 있으면 032-232-3245"으로 연락주시기 바랍니다"

In [41]:
import re

text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"
p = re.compile("[0-9]{3}-[0-9]{3}-[0-9]{4}")
m = p.findall(text)
print(m)

['032-232-3245']


In [1]:
import re

text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"
p = re.compile("\d+-\d+-\d+")
m = p.search(text)
print(m)

<re.Match object; span=(10, 22), match='032-232-3245'>


#### Q11. 정규표현식을 사용하여 text에서 에러가 들어간 부분만 포함하는 리스트를 출력하세요
text = "에러 1122, 레퍼런스 오류, 에러 1033, 아규먼트 오류, 에러 xxx"

In [59]:
import re

text = "에러 1122, 레퍼런스 오류, 에러 1033, 아규먼트 오류, 에러 xxx"

p = re.compile("[가-힣]{2}\s[0-9a-zA-Z]+")
m = p.findall(text)
print(m)

['에러 1122', '에러 1033', '에러 xxx']


#### Q12. 정규표현식을 사용하여 text에서 지역코드만 출력하세요.
text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"

In [78]:
import re

text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"
p = re.compile(r"\s\d{3}")
m = p.findall(text)
print(m)

[' 032']


#### Q13. 정규표현식을 사용하여 text에서 지역코드 제외하고 번호만 출력하세요.
text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"

In [72]:
import re

text = "문의사항이 있으면 032-232-3245으로 연락주시기 바랍니다"
p = re.compile(r"\d{3}-\d{4}")
m = p.findall(text)
print(m)

['232-3245']


#### Q14.'abcdefghij' 에 대하여 중첩을 적용한 서브그룹 5개로 컴파일하여 group()함수를 이용하여 'abcdefghi'와 e'를 출력하세요


In [91]:
import re

m = re.match('(((ab)(cd(e)fgh)i)j)', 'abcdefghij')
print(m.group(2),m.group(5))

abcdefghi e


#### Q15. 위 문제에서 모든 서브 그룹에 대한 문자열을 포함하는 튜플을 출력하세요.

In [92]:
m.groups()

('abcdefghij', 'abcdefghi', 'ab', 'cdefgh', 'e')

#### Q16. 이름으로 그룹을 참조하여 'Lots of punctuation 에서 Lots를 출력하세요.


In [4]:
# 그룹 이름 참조하기 => ?P<그룹이름>
import re

test="Lots of punctuation"
p = re.compile(r"(?P<func>\w+)\s+(?P<func1>\w+)")
m = p.search(test)
print(m.group('func'))

Lots


#### Q17. 'Paris is very very beautiful.'에서 'very very'를 출력하세요.


In [4]:
import re
li = 'Paris is very very beautiful.'
regex = re.compile('[a-z]{4}\s[a-z]{4}')
list = regex.findall(li)
print(list)

['very very']


#### Q18. 정규표현식을 작성하여 아래와 같이 출력하세요.

['1 apple', '5 oranges', '3 boys', '4 girls', '10 army', '11 mr']


In [3]:
import re
li = '1 apple, 5 oranges, 3 boys, 4 girls; 10 army| 11 mr'
regex = re.compile('\d+\s[a-z]+')
list = regex.findall(li)
print(list)

['1 apple', '5 oranges', '3 boys', '4 girls', '10 army', '11 mr']


#### Q19. text 에서 'H,h'만 출력하세요.
text = 'Hello my friend! Life is short you need Python!'


In [11]:
import re
text = 'Hello my friend! Life is short you need Python!'
regex = re.compile('(H|h)')
#regex = re.compile('[Hh]')
list = regex.findall(text)
print(list)

['H', 'h', 'h']


#### Q20. text 에서 'H,h'가 아닌 것 모두를 출력하세요.
text = 'Hello my friend! Life is short you need Python!'

In [16]:
import re
text = 'Hello my friend! Life is short you need Python!'
regex = re.compile('[^(H|h)]')
#regex = re.compile('^[Hh]')
list = regex.findall(text)
print(list)

['e', 'l', 'l', 'o', ' ', 'm', 'y', ' ', 'f', 'r', 'i', 'e', 'n', 'd', '!', ' ', 'L', 'i', 'f', 'e', ' ', 'i', 's', ' ', 's', 'o', 'r', 't', ' ', 'y', 'o', 'u', ' ', 'n', 'e', 'e', 'd', ' ', 'P', 'y', 't', 'o', 'n', '!']


####  Q.21.'we are going home'에서 home만 출력하세요.


In [3]:
import re
li = 'we are going home'
regex = re.compile('\w+$')
list = regex.findall(li)
print(list[0])

home


#### Q22. '199305, 1923A, a93247'에서 '199305'만 출력하세요.


In [29]:
import re
li = '199305, 1923A, a93247'
regex = re.compile('^\d+')
list = regex.findall(li)
print(list[0])

199305


#### Q23. '12345abc'에서 'abc'만 출력하세요.


In [28]:
import re
li = '12345abc'
regex = re.compile('[a-z]+')
list = regex.findall(li)
print(list[0])

abc


In [4]:
li = '12345abc'
print(li[5:8])

abc


In [5]:
text = '1234abc'
m = re.search('\D+',text)
m.group()

'abc'

In [7]:
text = '12345abc'
m = re.search('\d+',text)
m.group()

'12345'

In [12]:
text = '12345abc'
re.sub('[^0-9]','',text)

'12345'

#### Q24. '12345abc'에서 'a'만 출력하세요.


In [22]:
import re
li = '12345abc'
regex = re.compile('[a-z]')
list = regex.search(li)
print(list[0])

a


In [6]:
li = '12345abc'
m = re.search('[a-z]',li)
m.group(0)

'a'

#### Q25. 'abc12345Abc'에서 'A'만 출력하세요.


In [23]:
import re
li = 'abc12345Abc'
regex = re.compile('[A-Z]')
list = regex.search(li)
print(list[0])

A


# 07-22 과제

#### Q26. 'Banker'에서 'anker', 'banker123'에서 'banker'를 출력하세요


In [80]:
import re
li = 'Banker'
p = re.search('[a-z]+',li)
p.group()

'anker'

In [83]:
import re
li = 'banker123'
regex = re.search('[a-z]+',li)
regex.group()

'banker'

#### Q27. 'KOREA 대한민국'에서 '대'만 출력하세요.

In [21]:
import re
li = 'KOREA 대한민국'
regex = re.compile('([A-Z]+)\s(\w+)')
list = regex.search(li)
print(list[2][0])

대


#### Q28. text에서 'aaaaBBBcccDDDeee'을 모두 출력하세요.
text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'


In [75]:
import re
text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'
t = text[::-1][0:16]
print(t)

aaaaBBBcccDDDeee


In [76]:
t1 = re.search('a{4}B{3}c{3}D{3}e{3}',text)
t1.group()

'aaaaBBBcccDDDeee'

#### Q29. 아래의 경우에서 \<html>만 출력하세요
    - NON-GREEDY 방식 사용


In [85]:

text = '<html><head><title>Title</title></head><body></body></html>'

pattern = re.compile('<.*>')


print(len(text))
p = pattern.search(text)
p.group()


59


'<html><head><title>Title</title></head><body></body></html>'

In [87]:
text = '<html><head><title>Title</title></head><body></body></html>'
pattern = re.compile('<.*?>')
p = pattern.search(text)
p.group()


'<html>'

#### Q30. '1234a1234'에서  '1', '2', '3', '4'를 모두 출력하세요.


In [72]:
#nope
import re
li = '1234a1234'
m=re.findall('[^a]',li)
m

['1', '2', '3', '4', '1', '2', '3', '4']

# 07-25 과제

#### Q31. 

#### Q32. text에서 전체문장 모두 출력하세요.

In [92]:
# Q.
text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"
regex = re.compile('.*')
mo = regex.search(text)
print(mo.group())


what are you doing?


In [113]:
text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"
regex = re.compile(r'.*\n.*\n.*')
mo = regex.search(text)
print(mo.group())

what are you doing?
it is going to be late for school
we need to hurry up


In [124]:
text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"
regex = re.compile('.*',re.DOTALL) # DOTALL : 줄바꿈 문자 포함하여 출력
mo = regex.search(text)
print(mo.group())
#print(regex.findall(text))

what are you doing?
it is going to be late for school
we need to hurry up


#### Q33. text에서 대소문자 구분없이 전체문장 모두 출력하세요

text = 'Friend fRiend friEnd FRIEND'

In [4]:
import re 

reg = re.findall('friend', 'Friend fRiend friEnd FRIEND',re.IGNORECASE)

for groups in reg:
    print(groups)


Friend
fRiend
friEnd
FRIEND


#### Q34. 1609160537.371015을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.


In [137]:
#참고용, 날짜 형식 변환해줌
from dateutil.parser import parse
print(parse('Sat Jun 26 08:35:03 2021'))

2021-06-26 08:35:03


In [150]:
from datetime import datetime
import time

timestring=time.ctime(1609160537.371015)
timestring

'Mon Dec 28 22:02:17 2020'

In [5]:
from datetime import datetime

time = datetime.fromtimestamp(int(1609160537.371015))
time = time.strftime("%a %b %d %H:%S:%S %Y")
time


'Mon Dec 28 22:17:17 2020'

#### Q35. 현재 날짜와 시간을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.


In [181]:
now = datetime.now().ctime()
now

'Mon Jul 25 16:09:34 2022'

ctime() 함수는 주어진 timestamp를 현지 시간대 기준으로 소위 미국에서 흔히 사용되는 요 월 일 시:분:초 년 포멧으로 변환해줍니다. 그냥 간단하게 timestamp가 나타내는 날짜와 시간을 확인해보는 용도로 쓰기에 좋습니다.


# 07-26 과제

#### Q36. 현재 시간을 년-월-일 시:분:초로 출력하세요.

In [15]:
import time
from datetime import datetime

now = datetime.now()
print(now.strftime('%Y-%m-%d %H:%M:%S'))

2022-07-26 09:57:49


#### Q37. 현재 시간을 time.time을 불러와서 년-월-일 시:분:초로 출력하세요.

In [24]:
import time
from datetime import datetime

now = time.time()
now

1658797213.0851793

In [25]:
t = datetime.fromtimestamp(now)
print(t.strftime('%Y-%m-%d %H:%M:%S'))

2022-07-26 10:00:13


#### Q38. 올해 경과된 날짜수 계산하세요

In [28]:
import time
from datetime import datetime

now = time
print("올해로부터 경과된 일 : ", now.localtime().tm_yday)

올해로부터 경과된 일 :  207


In [33]:
from datetime import datetime

now  = datetime.now()
print("현재 :", now)

date_to_compare = datetime.strptime("20211231", "%Y%m%d")
print("비교할 날짜 :", date_to_compare)

date_diff = now - date_to_compare
print("차이 :", date_diff)

현재 : 2022-07-26 10:35:49.226365
비교할 날짜 : 2021-12-31 00:00:00
차이 : 207 days, 10:35:49.226365


#### Q39. 현재 요일을 "2021-6-26 오늘은 토요일입니다."와 같은 형식으로 출력하세요.

In [56]:
from datetime import datetime

now  = datetime.now()

a = now.strftime('%Y-%m-%d')

days = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
day = now.weekday()
#print(days[day])

b = days[day]

print(f'{a} 오늘은 {b}입니다.')

2022-07-26 오늘은 화요일입니다.


#### Q40. 1에서 백만까지 더하는데 걸리는 프로그램 실행 시간을 밀리초(ms) 단위로 구하세요.

In [62]:
import time

start = time.time()
for i in range(1000001):
    i += 1
end = time.time()

result = (end - start) * 0.01

print(f"{result:.5f} ms")


0.00063 ms


### 07-27 과제

#### Q41. 아래 코드를 보완하여 발생 가능한 모든 예외(정수, 인덱스, 미리 파악하지 못한 예외)를 처리한 후 마지막에  '모든 예외처리 완료'를 출력하세요.


In [ ]:
list_num = [52,273,32,72,100]

num_input = int(input('정수 입력> '))
print(f'{num_input}번째 요소: {list_num[num_input-1]}')


In [4]:
list_num = [52,273,32,72,100]

try:
    num_input = int(input('정수 입력> '))
    print(f'{num_input}번째 요소: {list_num[num_input-1]}')
except(ZeroDivisionError, IndexError,ValueError) as e:
    print(e)
    print('모든 예외처리 완료')

정수 입력> /.5
invalid literal for int() with base 10: '/.5'
모든 예외처리 완료


#### Q42. 기본가격 1000원인 2개의 상품에 대하여 임의의 추가 가격을 입력시 가격 조정한 결과를 반환하는 Price 클래스를 생성 후 객체를 만들어 price1, price2를 수행하세요. 
- price1 : 기본가격 + 추가가격
- price2 : (기본가격 + 추가가격) * 90%


In [33]:
import math

def Price():
    p1 = 1000
    p2 = 1000
    
    more = int(input('추가 가격을 입력하세요 > '))
    
    price1_1 = p1 + more
    price1_2 = p2 + more
    
    price2_1 = (p1 + more) * 0.9
    price2_1 = math.trunc(price2_1)
    price2_2 = (p2 + more) * 0.9
    price2_2 = math.trunc(price2_2)
    
    print(f'price1 = {price1_1}원,{price1_2}원')
    print(f'price2 = {price2_1}원,{price2_2}원')
    
Price()

추가 가격을 입력하세요 > 8000
price1 = 9000원,9000원
price2 = 8100원,8100원


#### Q43. strings를 문자의 크기 순서로 내림차순 정렬하세요


In [ ]:
strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']

In [2]:
strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']

strings.sort(key=len,reverse = True)
strings


['ababa', 'aaaa', 'bar', 'ca', 'a']

In [1]:
strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']
strings.sort(reverse=True)
strings

['ca', 'bar', 'ababa', 'aaaa', 'a']

#### Q44. strings를 다양한 문자가 포함된 순서로 정렬하세요


In [32]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']
strings.sort(key = lambda x:len(set(x)),reverse = True)
strings


['card', 'bar', 'foo', 'abab', 'aaaa']

#### Q45. 'abcde' 를 'edcba'로 바꾸어 출력하세요.(5가지 방법)

In [56]:
li = 'abcde'

#1 슬라이싱 이용
print(li[::-1])

#2 reverse 함수 이용
str_list = list(li)
str_list.reverse()
print(''.join(str_list))

#3 for문 이용
str_reverse = ''

for char in li:
    str_reverse = char + str_reverse

print(str_reverse)

#4 while문 이용
string_reversed=[]
i = len(li)
while i > 0: 
    string_reversed += li[i-1]
    i = i - 1 # decrement index
print(''.join(string_reversed)) 

#5 함수 이용
def reverse_string(li): 
    if len(li) == 0: 
        return li 
    else: 
        return reverse_string(li[1:]) + li[0] 
    
print(reverse_string(li))

edcba
edcba
edcba
edcba
edcba


# 07-28 과제

#### Q46. numbers 내부에 들어 있는 숫자가 몇 번 등장하는지를 출력하는 코드를 작성하세요.
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]


In [11]:
import collections

numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]

counts = collections.Counter(numbers)
print(counts)


Counter({3: 4, 6: 2, 5: 2, 8: 2, 2: 2, 9: 2, 7: 2, 4: 2})


#### Q47. 코딩을 한줄로 작성해서 동일한 결과를 출력하세요


In [3]:
# Q.
list = []
for i in range(0,20,2):
    list.append(i*i)
print(list)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


In [13]:
list = [i*i for i in range(0,20,2)]
list

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]

#### Q48. 반복문으로 팩토리얼을 구하는 사용자 함수를 작성하고 5!, 10!를 구하세요.


In [19]:
def factorial():
    a = int(input("숫자를 입력하세요 : "))
    result = 1
    for item in range(1, a+1, 1):
        result *= item 
    print(result)
    
factorial()

숫자를 입력하세요 : 5
120


In [20]:
factorial()

숫자를 입력하세요 : 10
3628800


#### Q49. 재귀란 '자기자신을 호출하는 것'을 의미한다. 재귀함수를 이용해서 팩토리얼을 구하는 사용자 함수를 작성하고 1!, 5!, 10!를 구하세요.
factorial(n) = n * factorial(n-1) (n >= 1)


In [23]:
def factorial(n):
    if n == 1:      
        return 1    
    return n * factorial(n - 1)  
 
print(factorial(1))
print(factorial(5))
print(factorial(10))

1
120
3628800


#### Q50. list a의 모든 원소를 실수형으로 바꾸어 출력하세요
a = [1,2,3,4,5]


In [27]:
a = [1,2,3,4,5]
li=[]
for i in a:
    li.append(float(i))
    
print(li)

[1.0, 2.0, 3.0, 4.0, 5.0]


In [2]:
a = [1,2,3,4,5]
list(map(float,a))



[1.0, 2.0, 3.0, 4.0, 5.0]

# 07-29 과제

#### Q31. 문자열 리스트 states를 정형화하여 아래와 같이 출력하세요.


In [ ]:
# Q. 
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
[출력]
['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']


In [70]:
import re

states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
result = str(states) 
result = result.title() # title함수 사용, 첫글자 대문자로
result = re.sub('[,]',',\n',result)
result = re.sub('^[\s+]','',result) #문자열 좌측 공백 제거
result = re.sub('[#?!]','',result) # 특수문자 #,? 제거



print(result)

['   Alabama ',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']


In [73]:
import re

states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
def form(word):
    word = word.strip()
    word = re.sub('[#?!]','',word)
    word = word.title()
    return word

list(map(form,states))

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

#### Q51. 게시물의 총 건수와 한 페이지에 보여 줄 게시물 수를 입력시 총 페이지 수를 출력하는 프로그램(func)


In [ ]:
# 서연님 코드 참고
def get_page_num(total_post,per_page):
    

#### Q52. 랜덤하게 1000명의 이름, 키와 몸무게 만들어 저장한 후 다시 불러내어 다음과 같이 출력하세요.

- 이름 :라바
- 몸무게: 80
- 키: 146
- BMI: 37.53049352598987
- 결과: 과체중


In [ ]:
# 민섭님 코드 참고

# 08-01 과제

#### Q53. 입력한 숫자를 천 단위로 구분하여 출력하세요.

In [4]:
# 민섭님 코드 참고
num = input('숫자를 입력하세요 > ')
if num.isdigit():
    num = num[::1]
    com=''
    for i,c in enumerate(num):
        i += 1
        if i != len(num) and i%3 == 0:
            com += (c,',')
        else:
            com += c
    com = com[::-1]
    print(com)
else:
    print('숫자를 입력하세요')


숫자를 입력하세요 > 75666


TypeError: can only concatenate str (not "tuple") to str

#### Q54. 카운터에서 거스름돈으로 사용할 500원, 100원, 50원, 10원짜리 동전이 무한히 존재한다고 가정한다. 손님에게 거슬러 줘야 할 돈이 n원일 때 거슬러 줘야 할 동전의 최소 개수를 구하세요. 단, 거슬러 줘야 할 돈 n원은 항상 10의 배수이다. n은 2750원이다.

In [95]:
import math
def coin():
    change = 2750

    coin_500 = int(change/500)
    coin_100 = int((change-(coin_500*500))/100)
    coin_50 = int((change-(coin_500*500+coin_100*100))/50)
    coin_10 = int((change-(coin_500*500+coin_100*100+coin_50*50))/10)
    
    print(f'500원:{coin_500}개, 100원:{coin_100}개, 50원:{coin_50}개, 10원:{coin_10}개')
    print(f'동전의 총개수: {coin_500+coin_100+coin_50+coin_10}')
    
coin()

500원:5개, 100원:2개, 50원:1개, 10원:0개
동전의 총개수: 8


In [5]:
n = 2750
count = 0

# 큰 단위의 화폐부터 차례대로 확인하기
coin_types = [500, 100, 50, 10]

for coin in coin_types:
    count += n // coin # 해당 화폐로 거슬러 줄 수 있는 동전의 개수 세기
    n %= coin

print(count)


8


#### Q55. data/mydata.txt 파일에 있는 단어 개수를 출력하세요.

In [1]:
li = ''
with open('./mydata.txt') as f:
    lines = f.readlines()
    li = ' '.join(lines)
    #li.append(lines)
    
print(li)

a lot of things occur each day
 we've got to live with on our way
 there's so much misery on the screen
 with commercials in between
 
 and the russians won't be so late
 uncle sam don't want to wait
 no matter if you're black or white
 you never ever had a right
 
 and look up to the eternal skies
 see warfare even there
 what once has been a paradise
 now destruction and despair
 
 in other worlds the children die
 lacking food ill from a fly
 oppressed by troops to tame their land
 it's all the same again
 
 if any man is free on earth
 then tormentors steal his birth
 they slam gun butts in his face
 and leave his woman choked in mace
 
 so stand up for our human rights
 push back this pest of hate
 raise you voice pass on the light
 unite! it's not too late
 
 how many tears flow away
 to become a sea of fears
 how many hearts are torn apart
 till another torment starts
 
 but before the world
 turns into a sun
 all cruelty and violence
 on earth will be dead and gone
 
 so stand 

In [46]:
li = ''
with open('./mydata.txt') as f:
    lines = f.readlines()
    li = ' '.join(lines)
    
    word = []
    words = li.split()
    word_counts = dict() #단어와 개수를 저장하기 위한 word_counts 사전을 생성
    total_count = 0
    
    for word in words:
        word_counts[word] = word_counts.get(word, 0) + 1    # 단어 카운트 증가

    for word, count in word_counts.items():
        print(word, count)
        total_count += count
        
    print(f'전체 단어 개수 : {total_count}')

a 6
lot 1
of 4
things 1
occur 1
each 1
day 1
we've 1
got 1
to 5
live 1
with 2
on 6
our 3
way 1
there's 1
so 4
much 1
misery 1
the 8
screen 1
commercials 1
in 4
between 1
and 6
russians 1
won't 1
be 2
late 3
uncle 1
sam 1
don't 1
want 1
wait 1
no 1
matter 1
if 2
you're 1
black 1
or 1
white 1
you 3
never 1
ever 1
had 1
right 1
look 1
up 3
eternal 1
skies 1
see 1
warfare 1
even 1
there 1
what 1
once 1
has 1
been 1
paradise 1
now 1
destruction 1
despair 1
other 1
worlds 1
children 1
die 1
lacking 1
food 1
ill 1
from 1
fly 1
oppressed 1
by 1
troops 1
tame 1
their 1
land 1
it's 3
all 2
same 1
again 1
any 1
man 1
is 1
free 1
earth 2
then 1
tormentors 1
steal 1
his 3
birth 1
they 1
slam 1
gun 1
butts 1
face 1
leave 1
woman 1
choked 1
mace 1
stand 2
for 2
human 2
rights 2
push 2
back 2
this 2
pest 2
hate 2
raise 2
voice 2
pass 2
light 2
unite! 2
not 2
too 2
how 2
many 2
tears 1
flow 1
away 1
become 1
sea 1
fears 1
hearts 1
are 1
torn 1
apart 1
till 1
another 1
torment 1
starts 1
but 1
before 1


In [49]:
# 선생님 솔루션
with open('./mydata.txt','r') as f:
    data = f.read()
    temp = data.split()
    print(f'전체 단어 수 : {len(temp)}')

전체 단어 수 : 213


#### Q56. 파일이름과 특정 단어를 인자로 입력하면 그 파일에 있는 특정 단어의 개수를 반환하는 사용자 함수를 이용하여 mydata 파일에서 how의 개수를 출력하세요.


In [53]:
def wordcount():
    file_name = input('파일 이름을 입력하세요 > ')
    find_word = input('찾고 싶은 단어를 입력하세요 > ')
    
    file=open('./'+file_name+'.txt',"r")
    
    sum=0
    for word_list in file:
        a = word_list.split(' ')
        for b in a:
            c = b.count(find_word)
            sum += c 
    print(f'{find_word}의 개수: {sum}')

In [55]:
wordcount()

파일 이름을 입력하세요 > mydata
찾고 싶은 단어를 입력하세요 > how
how의 개수: 2


In [56]:
# 선생님 솔루션
def countWord(filename, word):
    with open(filename, 'r') as f:
        text = f.read()
        text = text.lower()
        pos = text.find(word)
        count = 0
        while pos != -1:
            count += 1
            pos = text.find(word, pos+1)
    return count

filename = input('filename을 입력하세요: ')
word = input('filename에서 개수를 구할 단어를 입력하세요: ').lower()
ret = countWord(filename, word)
print(f'{word}의 개수: {ret}')

filename을 입력하세요: ./mydata.txt
filename에서 개수를 구할 단어를 입력하세요: How
how의 개수: 2


# 08-03 과제

### Q59.문자열을 입력받아 같은 문자가 연속적으로 반복되는 경우에 그 반복 횟수를 표시해 문자열을 압축하여 표시하세요.
- 예) "aaabbcccccca" -> a3b2c6a1

In [21]:
text = input("입력 : ") 
num = text[0] 
count = 1 
      
for i in range(1, len(text)): 
    if text[i] == num: 
        count += 1
    else: 
        print(num, end='') 
        print(count, end='') 
        count = 1 
        num = text[i] 
    
print(text[len(text)-1], end='') 
print(count) 


입력 : aaabbcccccca
a3b2c6a1


In [ ]:
from itertools import groupby
t = ''
''.join(f'{x}{len(list(y))} for x,y in groupby(x,y)')

# 08-04

### Q60.
N개의 배열로 이루어진 배열이 있을 때 주어진 수들을 M번 더하여 가장 큰 수를 만드는 프로그램을 작성하세요. 단 배열의 특정한 인덱스(번호)에 해당하는 수가 연속해서 K번을 초과하여 더해질 수 없는 것이 특징이다.
프로그램은 다음 조건을 만족하는 N, M, K를 공백으로 일차 입력하고 N개의 배열을 공백으로 이차 입력하면 결과물을 출력하는 방식으로 수행함.
- 2 <= N <= 1000
- 1 <= M <= 10000
- 1 <= K <= 10000


In [4]:
n, m, k = map(int, input().split())
x = list(map(int, input().split()))

x.sort()
first = x[n - 1]
second = x[n - 2]

count = int(m / (k + 1)) * k
count += m % (k + 1)

result = 0
result += (count) * first
result += (m-count) * second

print(result)

2 2 5
5


IndexError: list index out of range

In [7]:
# N, M, K를 공백을 기준으로 구분하여 입력 받기
n, m, k = map(int, input().split())
# N개의 수를 공백을 기준으로 구분하여 입력 받기
data = list(map(int, input().split()))

data.sort() # 입력 받은 수들 정렬하기
first = data[n - 1] # 가장 큰 수
second = data[n - 2] # 두 번째로 큰 수

# 가장 큰 수가 더해지는 횟수 계산
count = int(m / (k + 1)) * k
count += m % (k + 1)

result = 0
result += (count) * first # 가장 큰 수 더하기
result += (m - count) * second # 두 번째로 큰 수 더하기
 
print(result) # 최종 답안 출력


2 2 2
2 5 7 7
10


# 08-05

### Q61. file1, 2의 파일 크기를 각각 구하세요.

- file1 = 'data/stockcode.txt'
- file2 = 'data/img_sample.jpg'

In [2]:
from os.path import getsize

file1 = './stockcode.txt'
file2 = './img_sample.jpg'
file_size1 = getsize(file1)
file_size2 = getsize(file2)
print('File Name: %s \tFile Size: %d' %(file1, file_size1))
print('File Name: %s \tFile Size: %d' %(file2, file_size2))

File Name: ./stockcode.txt 	File Size: 15414
File Name: ./img_sample.jpg 	File Size: 170005


### Q62.
stockcode.txt의 105바이트 위치에서 500바이트를 읽어 그 내용은 stock_part.txt에 저장 한 후 출력하세요.


In [3]:
import os
with open('./stockcode.txt','rb') as f:
    f.seek(105,0)
    body = f.read(500)
with open('./stock_part.txt', 'wb') as f:
    f.write(body)
with open('./stock_part.txt', 'r') as f:
    print(f.read())

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 0: invalid continuation byte

# 08-09

### Q64.어떠한 수 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행하려고 한다. 단 두번째 연산은 N이 K로 나누어 떨어질 때만 선택할 수 있다.  N과 K를 입력했을 때 N이 1이 될 때까지 1번 혹은 2번의 과정을 수행해야 하는 최소 횟수를 구하는 프로그램을 완성하세요.

1. N에서 1을 뺀다.
2. N을 K로 나눈다.

입력 : N , K
    
반복
1.N에서 1을 뺀다.
2.N을 K로 나눈다.(나누어 떨어질 때만)

조건 : N이 1이 될 때까지 
    
결과 : 과정을 수행해야 하는 최소 횟수

In [1]:
def divide_program(N,K):
    count = 0
    while (N!=1):
        if (N%K==0):
            N = N//K
        else:
            N = N - 1
        count += 1
    return count


divide_program(13,6)

3

In [ ]:
손으로 정답 확인
N:13 ,K:6
1 : 13-1 = 12
2 : 12/6 = 2
3 : 2-1 = 1

In [2]:
divide_program(12,8)

5

In [ ]:
손으로 정답 확인
N:12,K:8
1 : 12-1 = 11
2 : 11-1 = 10
3 : 10-1 = 9
4 : 9-1 = 8
5 : 8/8 = 1

# 08-10

### Q65.아래와 같이 출력하는 코드를 작성하세요.

In [ ]:
*
**
***
****
*****

In [2]:
for i in range(6):
    print('*'*i)


*
**
***
****
*****


# 08-11

### Q66.아래와 같이 출력하는 코드를 작성하세요.

In [ ]:
     *
    ***
   *****
  *******
 *********
  *******
   *****
    ***
     *


In [30]:
for i in range(1,6):
    for j in range(5-i):
        print(' ',end="")
    for j in range(1,i*2,1):
        print('*',end="")
    print(' ')

for i in range(5):
    for j in range(i):
        print(' ',end="")
    for j in range(10,1+i*2,-1):
        print('*',end="")
    print(' ')

    * 
   *** 
  ***** 
 ******* 
********* 
********* 
 ******* 
  ***** 
   *** 
    * 


In [19]:
for i in range(-1,9,2):
    for j in range(9,-1,-2):
        print(' '*j+'*'*(i+2))

for i in range(9,-1,-2):
    for j in range(-1,9,2):
        print(' '*j+'*'*(i-2))


         *
       *
     *
   *
 *
         ***
       ***
     ***
   ***
 ***
         *****
       *****
     *****
   *****
 *****
         *******
       *******
     *******
   *******
 *******
         *********
       *********
     *********
   *********
 *********
*******
 *******
   *******
     *******
       *******
*****
 *****
   *****
     *****
       *****
***
 ***
   ***
     ***
       ***
*
 *
   *
     *
       *

 
   
     
       


### Q67.나무의 삼각형 부분과 밑동의 높이를 입력하면 해당하는 높이의 아래와 같은 나무를 출력하는 프로그램을 작성하세요.

In [ ]:
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
        ***
        ***
        ***


In [76]:
def make_tree(height):
    for i in range(1,1+height):
        print(" "*(height-i),"*"*(2*i-1))
        
    for i in range(1+height//5):
        print(" "*(height-1)+"***")
        
make_tree(30)

                              *
                             ***
                            *****
                           *******
                          *********
                         ***********
                        *************
                       ***************
                      *****************
                     *******************
                    *********************
                   ***********************
                  *************************
                 ***************************
                *****************************
               *******************************
              *********************************
             ***********************************
            *************************************
           ***************************************
          *****************************************
         *******************************************
        *********************************************
       ****

## 08-12

### Q68. 구구단을 출력하는 프로그램을 만드세요.

In [12]:
for i in range(2,10):
    print(f'----{i}단----')
    for j in range(1,10):
        print(f' {i}*{j} = {i*j}  ')

----2단----
 2*1 = 2  
 2*2 = 4  
 2*3 = 6  
 2*4 = 8  
 2*5 = 10  
 2*6 = 12  
 2*7 = 14  
 2*8 = 16  
 2*9 = 18  
----3단----
 3*1 = 3  
 3*2 = 6  
 3*3 = 9  
 3*4 = 12  
 3*5 = 15  
 3*6 = 18  
 3*7 = 21  
 3*8 = 24  
 3*9 = 27  
----4단----
 4*1 = 4  
 4*2 = 8  
 4*3 = 12  
 4*4 = 16  
 4*5 = 20  
 4*6 = 24  
 4*7 = 28  
 4*8 = 32  
 4*9 = 36  
----5단----
 5*1 = 5  
 5*2 = 10  
 5*3 = 15  
 5*4 = 20  
 5*5 = 25  
 5*6 = 30  
 5*7 = 35  
 5*8 = 40  
 5*9 = 45  
----6단----
 6*1 = 6  
 6*2 = 12  
 6*3 = 18  
 6*4 = 24  
 6*5 = 30  
 6*6 = 36  
 6*7 = 42  
 6*8 = 48  
 6*9 = 54  
----7단----
 7*1 = 7  
 7*2 = 14  
 7*3 = 21  
 7*4 = 28  
 7*5 = 35  
 7*6 = 42  
 7*7 = 49  
 7*8 = 56  
 7*9 = 63  
----8단----
 8*1 = 8  
 8*2 = 16  
 8*3 = 24  
 8*4 = 32  
 8*5 = 40  
 8*6 = 48  
 8*7 = 56  
 8*8 = 64  
 8*9 = 72  
----9단----
 9*1 = 9  
 9*2 = 18  
 9*3 = 27  
 9*4 = 36  
 9*5 = 45  
 9*6 = 54  
 9*7 = 63  
 9*8 = 72  
 9*9 = 81  


# 08-16

## Q69.
아래와 같이 입력하면 N X M 행렬 형태의 숫자 카드 중에서 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한 후 그 행에서 가장 숫자가 낮은 카드를 뽑아야 하는 규칙하에서 가장 높은 숫자가 쓰인 카드 한장의 숫자를 출력하는 프로그램을 작성하세요. 
- 첫번째 입력 : N X M 형열에 대하여 N(행), M(열)의 개수를 공백을 기준으로 입력(1<= N, M<=100)
- 두번째 입력 : 각 행의 숫자를 공백을 기준으로 입력. 단, 각 숫자는 1 이상 10000 이하의 자연수임.

In [ ]:
- 입력 : 
    1. N(행), M(열) / (1<= N, M<=100) 
    2. 각 행의 숫자, 공백 기준 / 1<자연수<=10000 / for문
    
- 조건 : 
    1. 뽑고자 하는 숫자가 있는 행 선택
    2. 해당 행에서 가장 숫자가 낮은 것을 뽑기

- 출력 : 가장 높은 숫자

In [5]:
import pandas as pd

def high_card_pick():
    
    # 행렬 입력
    nm = input(' N X M 행렬에서 공백을 기준으로 N과 M을 입력하세요 > ')
    print('='*100)
    n = nm.split(' ')[0]
    n = int(n)
    m = nm.split(' ')[1]
    m = int(m)
    
    # 각 행의 숫자 입력 : 행의 수 만큼 반복
    row_nums = []
    for i in range(n):
        row_num_input = input(f'{i}행의 숫자를 공백을 기준으로 입력하세요 > ')
        row_num = row_num_input.split(' ')
        
        # 열의 수만큼 입력하는 지 확인
        if len(row_num) <= m :
            row_nums.append(row_num)
        else :
            break
    
    df = pd.DataFrame(row_nums)
    df = df.astype(int) # 데이터프레임 전체 요소 str -> int
    print(df)
    print('='*100)
    
    # 뽑고자 하는 숫자가 있는 횟수와 행 선택
    times = int(input('카드를 뽑을 횟수를 입력하세요 > '))
    
    row_pick_mins = []
    for li in range(times):
        row_pick = int(input('뽑고자 하는 숫자가 있는 행을 입력하세요 > '))
        row_pick_min = df.loc[row_pick].min()
        row_pick_mins.append(row_pick_min)
        
    print(max(row_pick_mins))


In [6]:
high_card_pick()

 N X M 행렬에서 공백을 기준으로 N과 M을 입력하세요 > 3 3
0행의 숫자를 공백을 기준으로 입력하세요 > 1 2 3
1행의 숫자를 공백을 기준으로 입력하세요 > 4 5 6
2행의 숫자를 공백을 기준으로 입력하세요 > 7 8 9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
카드를 뽑을 횟수를 입력하세요 > 3
뽑고자 하는 숫자가 있는 행을 입력하세요 > 0
뽑고자 하는 숫자가 있는 행을 입력하세요 > 1
뽑고자 하는 숫자가 있는 행을 입력하세요 > 2
7


In [7]:
# 구글링 답안 예시1_ min() 함수를 이용하여 푸는 예시
n, m = map(int, input().split())

result = 0

# 한 줄씩 입력받아 확인
for i in range(n):
    data = list(map(int, input().split()))
    # 현재 줄에서 '가장 작은 수 찾기'
    min_value = min(data)
    # '가장 작은 수'들 중에서 가장 큰 수 찾기
    result = max(result, min_value)

print (result)

2 2
1 4 5
3
3


In [ ]:
# 구글링 답안 예시_ 2중 반복문 구조를 이용하는 예시
n, m = map(int, input().split())

result = 0

# 한 줄씩 입력받아 확인
for i in range(n):
    data = list(map(int, input().split()))
    # 현재 줄에서 '가장 작은 수 찾기'
    min_value = 10001  # 각 숫자는 1이상 10,000이하의 자연수
    for a in data:
        min_value = min(min_value, a)
    # '가장 작은 수'들 중에서 가장 큰 수 찾기
    result = max(result, min_value)

print(result)

In [21]:
nm = '3 4'
n = nm.split(' ')
print(n)

['3', '4']


In [29]:
# 행열 수에 맞춰 입력받기
row_nums = []
for i in range(3):
    row_num = input(f'{i}행의 숫자를 공백을 기준으로 입력해주세요 > ')
    n1 =  row_num.split(' ')
    if len(n1)<3: 
        row_nums.append(n1)
    else:
        break
print(row_nums)

0행의 숫자를 공백을 기준으로 입력해주세요 > 1 2
1행의 숫자를 공백을 기준으로 입력해주세요 > 2 3
2행의 숫자를 공백을 기준으로 입력해주세요 > 5 6
[['1', '2'], ['2', '3'], ['5', '6']]


In [53]:
# 시리즈로 만들기
import pandas as pd
row_nums = []
for i in range(3):
    row_num = input(f'{i}행의 숫자를 공백을 기준으로 입력해주세요 > ')
    n1 =  row_num.split(' ')
    if len(n1)<3: 
        row_nums.append(n1)
    else:
        break
df = pd.DataFrame(row_nums)
df = df.astype(int)
print(df)

0행의 숫자를 공백을 기준으로 입력해주세요 > 3 5
1행의 숫자를 공백을 기준으로 입력해주세요 > 3 4
2행의 숫자를 공백을 기준으로 입력해주세요 > 1 4
   0  1
0  3  5
1  3  4
2  1  4


In [54]:
df.dtypes

0    int64
1    int64
dtype: object

In [77]:
print(df.loc[0])
a = df.loc[0].min()
print(a)

0    3
1    5
Name: 0, dtype: int64
3


# 08-17

### Q70. 
min max 함수, 정렬 등의 방법으로 풀었다. 위 문제를 다중 for문을 사용하여 풀어보세요.

### Q71.
여행가 A는 N X N 크기의 정사각형 공간에 서 있다. A는 6개의 이동 명령 계획에 따라 움직이게 된다. 이동 명령은 L(왼쪽), R(오른쪽), U(윗쪽), D(아랫쪽)로 구성되며 R R R U D D와 같이 6개이다. 정사각형 공간을 벗어나는 움직임은 무시된다. 언급한 규칙에 따라 N과 이동 명령 계획으로 각각 5와 R R R U D D를 입력하면 A의 공간 좌표는 3 4가 된다. 이동 명력 계획서가 주어질 때 A가 최종적으로 도착할 지점의 좌표를 출력하는 프로그램을 작성하시오.


In [ ]:
(1,1)(1,2)(1,3)(1,4)
               (2,4)
               (3,4)

- 입력 :   N X N / L(왼쪽), R(오른쪽), U(윗쪽), D(아랫쪽)
- 조건 : 정사각형 공간을 벗어나는 움직임은 무시
- 출력 : 도착할 지점의 좌표

In [ ]:
n = input('정사각형의 크기 입력 > ')
a, b = map(int, input('처음 위치 입력 > ').split())
move=[]
move = input('6개의 이동 명령 입력 > ').split()

if move == 'L':
    if a<0 or a<n
    a = a-1

# 08-18

## Q72.
정수 N이 입력되면 00시 00분 00초부터 N시 59분 59초까지의 모든 시각 중에서 3이 하나라도 포함되는 모든 경우의 수를 구하는 프로그램을 작성하시오.(0<= N <=23)


In [ ]:
00시 02분 03초
00시 27분 45초
7 -> 14625

In [ ]:
- 입력 : 정수 N (0<= N <=23)
- 조건 : 3이 하나라도 포함되는 모든 경우 
- 출력 : 조건의 카운트

In [ ]:
000003
000030
000300
003000
030000
005959

In [1]:
N = int(input('정수 N > '))
sum = 0
num = ''
for i in range(N+1):
    si = str(i)
    for j in range(60):
        bun = str(j)
        for k in range(60):
            cho = str(k) 
            num = si+bun+cho
            
            if '3' in num:
                sum += 1
            else:
                pass
print(sum)
print((N+1)*3600)

정수 N > 7
14625
28800


# 08-19

### Q73.행 위치는 1~8로 열 위치는 a ~ h로 표현하는 8 x 8 좌표 평면상에서 특정 위치가 주어졌을 때 아래 조건하에서 그 위치에서 이동할 수 있는 경우의 수를 출력하는 프로그램을 작성하세요.
- 수평으로 두 칸 이동한 뒤에 수직으로 한 칸 이동
- 수직으로 두 칸 이동한 뒤에 수평으로 한 칸 이동
- 8 x 8 좌표 평면을 나갈 수 없음


In [ ]:
(-1,-2)(1,-2)
(2,1)(-2,-1)
b3

In [1]:
cols = [chr(i) for i in range(ord('a'),ord('h')+1)]
rows = list(range(1,9))

steps = [(-2,-1),(-2,1),(2,-1),(2,1),(1,-2),(-1,-2),(1,2),(-1,2)]

def solution(start):
    ans = 0 # 경우의 수
    
    r = rows.index(int(start[1])) + 1
    c = cols.index(start[0])+1
    
    for step in steps:
        next_r = r + step[0]
        next_c = c + step[1]
        if next_r >= 1 and next_r<=9 and next_c >= 1 and next_c<=8:
            ans += 1
            
    print(ans)
    return ans


start = 'c2'
solution(start)    

6


6

# 08-22

### Q74.
캐릭터는 매뉴얼에 따라 이동한다. 아래 입력조건에 따라 캐릭터가 방문한 칸의 수를 출력하는 프로그램을 작성하세요.

- 입력조건
  - 첫째 줄에 맵의 세로 크기 N과 가로 크기 M을 공백으로 구분하여 입력 (3 <= N,M <=50)
  - 둘째 줄에 게임 캐릭터가 있는 칸의 좌표 (A,B)와 바라보는 방향 d가 각각 서로 공백으로 구분하여 입력(방향 d의 값으로는 북, 동, 남, 서가 각각 0,1,2,3)
  - 세째 줄에 맵이 육지인지 바다인지에 대한 정보 입력(육지 0, 바다 1) N개의 줄에 맵의 상태가 북쪽으로 부터 남쪽순서대로 각 줄의 데이터는 서쪽부터 동쪽 순서대로 주어진다.
  - 처음에 캐릭터가 위치한 칸의 상태는 항상 육지이다.


- 매뉴얼<BR>
  캐릭터가 있는 장소는 1 X 1 크기의 정사각형으로 이루어진 N X M 크기의 직사각형으로 각각의 칸은 육지 또는 바다이다.캐릭터는 동서남북 중 한 곳을 바라본다. 맵의 각 칸은 (A, B)로 나타낼 수 있고 A는 북쪽으로부터 떨어진 칸의 개수, B는 서쪽으로부터 떨어진 칸의 개수이다.캐릭터는 상하좌우로 움직일 수 있고 바다로 되어 있는 공간에는 갈 수 없다. 캐릭터의 움직임 설정을 위한 매뉴얼은 아래와 같다.
  - 현재 위치에서 현재 방향을 기준으로 왼쪽 방향부터 차례대로 갈 곳을 정한다.
  - 캐릭터의 바로 왼쪽 방향에 아직 가보지 않은 칸이 존재한다면 왼쪽 방향으로 회전한 다음 왼쪽으로 한 칸을 전진한다. 왼쪽 방향에 가보지 않은 칸이 없다면 왼쪽 방향으로 회전만 수행하고 1단계로 돌아간다.
  - 만약 네 방향 모두 이미 가본 칸이거나 바다로 되어 있는 칸인 경우에는 바라보는 방향을 유지한 채로 한 칸 뒤로 가고 1단계로 돌아간다. 단, 이때 뒤쪽 방향이 바다인 칸이라 뒤로 갈수 없는 경우에는 움직임을 멈춘다.


In [ ]:
0 0 0
1 1 0
1 1 0

- 입력 : 
    - 세로 N 가로 M (3 <= N,M <=50)
        N M
    - 캐릭터 현재 좌표 (A,B), 바라보는 방향 d (북, 동, 남, 서가 각각 0,1,2,3 // 시계방향)
        A B d
    - 맵 채우기 : 육지 0 바다 1
        0 or 1
- 조건 :
    - 행열로 이루어짐
    - 처음 캐릭터가 위치한 칸은 항상 육지 -> 0
    - 상하좌우 움직
    - 바다는 갈 수 없다

- 무브 : 
    1. 입력받은 방향 d를 기준으로 왼쪽 방향 행+-1 or 열+-1
        - 왼쪽 방향에 아직 가보지 않은 칸이 존재? 그 방향으로 전진
    2. 왼쪽 방향에 가보지 않은 칸이 없다면 왼쪽 방향으로 회전만 수행하고 1단계로 돌아감
    3. 만약 네 방향 모두 이미 가본 칸이거나 바다(1)로 되어 있는 칸인 경우 -> 바라보는 방향을 유지한 채 한 칸 뒤로
        - 이때 뒤쪽 방향이 바다(1)인 칸이라 뒤로 갈수 없는 경우에는 스탑
        
        
- 출력 : 캐릭터가 방문한 칸의 수

In [9]:
import numpy as np

def turtle_trip():
    N,M = map(int,input('N M > ').split(' '))

    if N<3 or (M>50 and M<0):
        pass
    else:
        A,B,d = map(int,input('A B d > ').split(' '))
    
    base_map = np.arange(N*M).reshape(N,M)
    
    for i in range(N):
        for j in range(M):
            base_map[i,j] = int(input('바다:1 육지:0 > '))
            

    row = A
    col = B
    
    base_map[row,col] = 0
    cnt = 0
    
    print(f'\n 처음 지도 \n {base_map} \n')
    try:
        while(True):
            # 북쪽 방향
            if d == 0:
                if base_map[row,col-1] == 1:
                    row = row+1
                    cnt += 1
                elif base_map[row,col-1] == 0:
                    base_map[row,col-1] = 1
                    cnt += 1
                    d = 3
                    col = col-1
                else:
                    pass

            # 동쪽 방향
            if d == 1:
                if base_map[row-1,col] == 1:
                    col = col-1
                    cnt += 1
                elif base_map[row-1,col]== 0:
                    base_map[row-1,col]=1
                    cnt += 1
                    d = 0
                    row = row-1
                else :
                    pass

            # 남쪽 방향   
            if d == 2:
                if base_map[row,col+1] == 1:
                    row = row-1
                    cnt += 1
                elif base_map[row,col+1] == 0:
                    base_map[row,col+1] =1
                    cnt += 1
                    d = 1
                    col = col+1
                else :
                    pass            

            # 서쪽 방향       
            if d == 3:
                if base_map[row+1,col] == 1:
                    col = col+1
                    cnt += 1
                elif base_map[row+1,col] == 0:
                    base_map[row+1,col] =1
                    cnt += 1
                    d = 2
                    row = row+1
                else :
                    pass
    except:
        print(f'거북이가 방문한 칸의 수 : {cnt}\n')
        print(f'거북이가 그린 지도 \n {base_map}')

turtle_trip()

N M > 4 4
A B d > 1 1 0
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1

 처음 지도 
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]] 

거북이가 방문한 칸의 수 : 3

거북이가 그린 지도 
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [2]:
import numpy as np

N,M = map(int,input('N M >').split(' '))
if N<3 or (M>50 and M<0):
    pass
else:
    A,B,d = map(int,input('A B d >').split(' '))

print(N)
print(M)
print(A)
print(B)
print(d)

N M >3 3
A B d >1 1 1
3
3
1
1
1


In [4]:
N,M = map(int,input('N M > ').split(' '))

if N<3 or (M>50 and M<0):
    pass
else:
    
    A,B,d = map(int,input('A B d > ').split(' '))
    
    base_map = np.arange(N*M).reshape(N,M)
    
    for i in range(N):
        for j in range(M):
            base_map[i,j] = int(input('바다:1 육지:0 > '))
    
    
print(base_map)

N M > 3 3
A B d > 1 1 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 1
[[1 1 0]
 [0 1 1]
 [0 0 1]]


In [5]:
N,M = map(int,input('N M > ').split(' '))

if N<3 or (M>50 and M<0):
    pass
else:
    
    A,B,d = map(int,input('A B d > ').split(' '))
    
    base_map = np.arange(N*M).reshape(N,M)
    
    for i in range(N):
        for j in range(M):
            base_map[i,j] = int(input('바다:1 육지:0 > '))
    
    base_map[A,B] = 0
    
print(base_map)

N M > 3 3
A B d > 1 1 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
N,M = map(int,input('N M > ').split(' '))

if N<3 or (M>50 and M<0):
    pass
else:
    
    A,B,d = map(int,input('A B d > ').split(' '))
    
    base_map = np.arange(N*M).reshape(N,M)
    
    for i in range(N):
        for j in range(M):
            base_map[i,j] = int(input('바다:1 육지:0 > '))

    row = A
    col = B
    
    base_map[row,col] = 0
    cnt = 0
    
    try:
        while(True):
            # 북쪽 방향
            if d == 0:
                if base_map[row,col-1] == 1:
                    row = row+1
                    print('북빽')
                elif base_map[row,col-1] == 0:
                    base_map[row,col-1] = 1
                    cnt += 1
                    d = 3
                    col = col-1
                    print('북완')
                else:
                    pass

            # 동쪽 방향
            if d == 1:
                if base_map[row-1,col] == 1:
                    col = col-1
                    print('동빽')
                elif base_map[row-1,col]== 0:
                    base_map[row-1,col]=1
                    cnt += 1
                    d = 0
                    row = row-1
                    print('동완')
                else :
                    pass

            # 남쪽 방향   
            if d == 2:
                if base_map[row,col+1] == 1:
                    row = row-1
                    print('남빽') 
                elif base_map[row,col+1] == 0:
                    base_map[row,col+1] =1
                    cnt += 1
                    d = 1
                    col = col+1
                    print('남완')
                else :
                    pass            

            # 서쪽 방향       
            if d == 3:
                if base_map[row+1,col] == 1:
                    col = col+1
                    print('서빽') 
                elif base_map[row+1,col] == 0:
                    base_map[row+1,col] =1
                    cnt += 1
                    d = 2
                    row = row+1
                    print('서완') 
                else :
                    pass
    except:
        print(f'거북이가 방문한 칸의 수 : {cnt}')
        print(f'거북이가 그린 지도 \n {base_map}')


N M > 3 3
A B d > 1 1 0
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 1
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 0
바다:1 육지:0 > 0
북빽
북완
거북이가 방문한 칸의 수 : 1
거북이가 그린 지도 
 [[0 0 1]
 [1 0 0]
 [1 0 0]]


# 08-24

In [1]:
#스택 : 박스 쌓기에 비유. 선입후출 구조

stack=[]
stack.append(5)
stack.append(2)
stack.append(3)
stack.append(7)
stack.pop()
stack.append(1)
stack.append(4)
stack.pop()

print(stack)
print(stack[::-1])


[5, 2, 3, 1]
[1, 3, 2, 5]


In [3]:
# 큐 : 먼저 온 사람이 먼저 나간다. 선입선출 구조

from collections import deque
queue = deque()

queue.append(5)
queue.append(2)
queue.append(3)
queue.append(7)
queue.popleft()
queue.append(1)
queue.append(4)
queue.popleft()

print(queue)
queue.reverse()
print(queue)

deque([3, 7, 1, 4])
deque([4, 1, 7, 3])


## Q75.
N X M 크기의 얼음 틀로 한번에 만들 수 있는 아이스크림의 개수를 아래 입력조건에 따라 출력하는 프로그램을 DFS(Depth First Search)를 이용하여 작성하세요.
 
- 입력조건
  - 첫번째 줄에 얼음 틀의 세로 길이 N과 가로 길이 M이 주어진다.(1 <= N,M <= 1000)
  - 두번째 줄부터 N+1번째 줄까지 얼음 틀의 형태가 주어진다.
  - 이때 구멍이 뚫려있는 부분은 0 그렇지 않은 부분은 1이다.
  - 구멍이 뚫려 있는 부분끼리 상, 하, 좌, 우로 붙어 있는 경우 서로 연결되어 있는 것으로 간주한다.


In [ ]:
너비 우선은 매 단계에서 가능한 모든 경우의 수를 확인,
깊이 우선은 한 우물만 파고들며 끝을 볼 때까지 확인! 이라는 것만 이해하면 다 이해한 겁니다! 👍
https://jeinalog.tistory.com/18

In [ ]:
5 5
00110
00011
11111
00111
11000

얼음 4개 생성

In [ ]:
- 입력 : N x M 행렬(1 <= N,M <= 1000)
        행렬의 요소 한 행씩 입력 (0:구멍 1:막힘)
- 조건 : 구멍(0)으로 붙어있는 경우 연결된 것임
    
        깊이 우선 탐색 사용.  
        좌:(0,-1) 우:(0,1) 상:(-1,0) 하:(1,0) 
        처음 만난 0 방문 -> 인접노드 탐색 -> 1로 바꿔줌(지나갔다는 표시) -> 이동
        
- 출력 : N X M 크기의 얼음 틀로 한번에 만들 수 있는 아이스크림의 개수

In [43]:
import numpy as np

N,M = map(int,input('N x M 행렬 공백을 기준으로 입력 > ').split(' '))

if (1 > N) or (M > 1000):
    pass
else:
    ice_mold = [list(map(int, input().split())) for _ in range(N)]
    arr = np.array(ice_mold)
    
    row = 0
    col = 0
    
    
#print(N,M)
print(arr)

N x M 행렬 공백을 기준으로 입력 > 2 1001
[[0]
 [0]
 [0]]


In [39]:
mold = [list(map(int, input().split())) for _ in range(3)]
print(mold)
arr1 = np.array(mold)
print(arr1)

1 1 0 0
0 0 1 1
1 0 0 1
[[1, 1, 0, 0], [0, 0, 1, 1], [1, 0, 0, 1]]
[[1 1 0 0]
 [0 0 1 1]
 [1 0 0 1]]


In [50]:
arr = np.arange(16).reshape(4,4)

row = 0
col = 0

ice = arr[row,col]
print(ice)

8


In [ ]:
def DFS(arr):
    
    stack=[]
    
    row = 0
    col = 0
    
    find = [(0,-1),(0,1),(-1,0),(1,0)]
    
    for i in find:
        arr[row+i,col+i]
        if arr[row,col] == 0:
            arr[row,col] = 1
            stack.append()

In [ ]:
stack=[]
stack.append(5)
stack.append(2)
stack.append(3)
stack.append(7)
stack.pop()
stack.append(1)
stack.append(4)
stack.pop()

print(stack)
print(stack[::-1])

In [5]:
arr = [(1,1),(2,2)]
find = [(0,-1),(0,1),(-1,0),(1,0)]
row = 0
col = 0
for i in find:
    arr = arr[row+i[0],col+i[1]]
    print(arr)

TypeError: list indices must be integers or slices, not tuple

# 08-25

### Q76. 10!을 재귀함수를 이용하여 출력하세요.

In [6]:
def factorial_iterative(n):
    result = 1
    for i in range(1,n+1):
        result *= i
    return result

factorial_iterative(10)

3628800

In [1]:
def factorial(n):
    if n==1:
        return 1
    return n*factorial(n-1)

In [2]:
factorial(10)

3628800

# 08-26

## Q77.
N X M 크기의 미로에는 여러마리의 괴물이 있어 이를 피해 탈출해야 한다. 주인공의 위치는 (1,1)이고 미로의 출구는 (N,M)의 위치에 존재하며 한번에 한칸씩 이동할 수 있다. 괴물이 있는 부분은 0, 없는 부분은 1로 표시되어 있으며 미로는 반드시 탈출할 수 있는 형태로 제시된다. 주인공이 탈출하기 위해 움직여야 하는 최소 칸의 개수를 구하세요. 칸을 셀 때는 시작 칸과 마지막 칸을 모두 포함하여 계산하고 입력 조건은 아래와 같다.(BFS를 이용)
- 첫째 줄에 두 정수 N,M(4<=N,M<=200)이 주어진다.
- 다음 N개의 줄에는 각각 M개의 정수(0 혹은 1)로 미로의 정보가 주어진다. 각각의 수들은 공백없이 붙여서 입력으로 제시된다.
- 또한 시작칸과 마지막칸은 항상 1이다.

In [ ]:
5 5
11011
01011
01111
11011
10111

9

- 입력 : N,M(4<=N,M<=200)
        공백없이 0,1 각각 입력
        시작칸과 마지막칸은 항상 1
        
- 조건 : 주인공의 처음위치는 (1,1)
        미로의 출구는 (N,M)
        한번에 한칸씩 이동
        1 : 이동 가능 , 0: 불가능
        미로는 반드시 탈출할 수 있는 형태로 제시
        칸을 셀 때는 시작 칸과 마지막 칸을 모두 포함하여 계산

- 출력 : 주인공이 탈출하기 위해 움직여야 하는 최소 칸의 개수

In [3]:
import numpy as np

N,M = map(int,input('N,M > ').split(','))

if (4 > N or M > 200):
    pass

else: 
    arr = [list(map(int, input('1 : 이동 가능 , 0: 불가능 > ').strip())) for _ in range(M)]
    arr = np.array(arr)
    
    arr[1,1] = 1
    arr[N-1,M-1] = 1

print(arr)

def bfs(x,y):
    visited = [x,y]
    queue = [x,y]
    while queue:
        v = queue.pop(0)
        for w in arr[v]:
            if w not in visited:
                visited.append(w)
                queue.append(w)
    return visited
    
cnt = 0
for i in range(1,N):
    for j in range(1,M):
        if bfs(i,j) == 1:
            cnt += 1
            
print(cnt)
print(arr)

N,M > 5,5
1 : 이동 가능 , 0: 불가능 > 11111
1 : 이동 가능 , 0: 불가능 > 11111
1 : 이동 가능 , 0: 불가능 > 11111
1 : 이동 가능 , 0: 불가능 > 11111
1 : 이동 가능 , 0: 불가능 > 11111
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
0
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
import numpy as np

N,M = map(int,input('N,M > ').split(','))

arr = [list(map(int, input('1 : 이동 가능 , 0: 불가능 > ').strip())) for _ in range(M)]

arr = np.array(arr)

print(arr)

N,M > 2,2
1 : 이동 가능 , 0: 불가능 > 10
1 : 이동 가능 , 0: 불가능 > 01
[[1 0]
 [0 1]]


In [6]:
import numpy as np

N,M = map(int,input('N,M > ').split(','))

if (4 > N or M > 200):
    pass

else: 
    arr = [list(map(int, input('1 : 이동 가능 , 0: 불가능 > ').strip())) for _ in range(M)]
    arr = np.array(arr)
    
    arr[1,1] = 1
    arr[N-1,M-1] = 1

print(arr)

N,M > 4,4
1 : 이동 가능 , 0: 불가능 > 0000
1 : 이동 가능 , 0: 불가능 > 0000
1 : 이동 가능 , 0: 불가능 > 0000
1 : 이동 가능 , 0: 불가능 > 0000
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [ ]:
#정답
from collections import deque

# N, M을 공백으로 구분하여 입력받기
n,m=map(int,input().split())

# 2차원 리스트의 맵 정보 입력받기
graph=[]
for i in range(n):
    graph.append(list(map(int,input())))

# 이동할 네 방향 정의(상, 하, 좌, 우), x는 위쪽에서 떨어진 위치, y는 좌측에서 떨어진 위치 
dx = [-1,1,0,0]
dy = [0,0,-1,1]

# BFS 소스코드 구현
def bfs(x,y):
    # 큐 구현을 위해 deque 라이브러리 사용
    queue = deque()
    queue.append((x,y))
    # 큐가 빌 때까지 반복
    
while queue:
        x,y = queue.popleft()
        # 현재 위치에서 네 방향으로의 위치 확인
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            # 미로 찾기 공간을 벗어난 경우 무시
            if nx < 0 or ny < 0 or nx >= n or ny >=m:
                continue
                # 괴물인 경우 무시
            if graph[nx][ny] == 0:
                continue
                # 해당 노드를 처음 방문하는 경우에만 최단 거리 기록
            if graph[nx][ny] == 1:
                graph[nx][ny] =graph[x][y] + 1
                queue.append((nx,ny))
                
    # 가장 오른쪽 아래까지의 최단 거리 반환(이동할 때마다 1씩 추가하기 때문에 탈출시에 최종 이동한 칸의 개수가 만들어짐)
            return graph[n-1][m-1]

# BFS를 수행한 결과 출력
print(bfs(0,0))



# 08-30

## Q78.
```
소수란 2보다 큰 자연수 중에서 1과 자기자신을 제외한 자연수로는 나누어떨어지지 않는 자연수이다. 
어떠한 자연수가 소수인지 아닌지 판별하는 프로그램을 작성하세요.
```

In [7]:
def sosu(n):
    if n <= 2:
        return False
    else :
        for i in range(2,n):
            if n%i == 0:
                return False
        return True

sosu(12)

False

In [ ]:
# 답
def is_prime_number(x):
    for i in range(2,x):
        if x % i == 0:
            return False
    return True
print(is_prime_number(4))


# 08-31

## Q79.
M 이상 N 이하의 소수를 모두 출력하는 프로그램을 작성하세요.
- 입력조건
  - 첫째 줄에 자연수 M과 N이 빈칸을 사이에 두고 주어진다.(1<=M<=N<=1,000,000)
  - 단 M이상 N 이하의 소수가 하나 이상 있는 입력만 주어진다.


In [1]:
def sosu(n):
    if n <= 2:
        return False
    else :
        for i in range(2,n):
            if n%i == 0:
                return False
        return True
    
M,N = map(int,input('숫자 입력 > ').split())

li = []
if M>N or M<1 or N<1 or N>1000000:
    M,N
else:
    for i in range(M,N):
        if sosu(i)== True:
            li.append(i)
    print(li)

숫자 입력 > 3 3000
[3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 12

# 09-02

#### Q80.
```
암호는 서로 다른 L개의 알파벳 소문자들로 구성되며 최소 한 개의 모음(a, e, i, o, u)과 최소 두 개의 자음으로 구성되어 있다고 알려져 있다. 또한 정렬된 문자열을 선호하는 직원들의 성향으로 미루어 보아 암호를 이루는 알파벳이 암호에서 증가하는 순서로 배열되었을 것이라고 추측된다. 즉, abc는 가능성이 있는 암호이지만 bac는 그렇지 않다. 새 보안 시스템에서 직원들이 암호로 사용했을 법한 문자의 종류는 C가지가 있다고 한다. 이 알파벳을 입수한 james, kevin 형제는 직원들의 방에 침투하기 위해 암호를 추측해 보려고 한다. C개의 문자들이 모두 주어졌을 때, 가능성 있는 암호들을 모두 구하는 프로그램을 다음 사항에 유의하여 작성하시오.

- 첫째 줄에 두 정수 L, C가 주어진다. (3 ≤ L ≤ C ≤ 15) 다음 줄에는 C개의 문자들이 공백으로 구분되어 주어진다. 주어지는 문자들은 알파벳 소문자이며, 중복되는 것은 없다.

- 각 줄에 하나씩, 사전식으로 가능성 있는 암호를 모두 출력한다.

```

```
[내가 정리]

- 입력
    알파벳 개수 : L, 조합 : C (3 ≤ L ≤ C ≤ 15)
    * C개의 문자들 (공백 구분 / 소문자 / 중복x)
    
- 조건 
    한 개의 모음(a, e, i, o, u) 이상 + 두 개의 자음 이상
    a~z : 1~15 라고 하면 오름차순
   
- 출력 
    딕셔너리 형태로 모든 암호 조합 출력

```

In [10]:
L, C = map(int,input('L,C > ').split(','))

if (L < 3) or (L > C) or (L > 15) or (C > 15) or (C < 3):
    pass
else : 
    for i in range(C):
        
    print(L)
    print(C)

L,C > 5,9
5
9


# 09-05

#### Q81.
파이썬의 itertools 라이브러리를 활용하여 리스트 data = ['A','B','C']로 부터 아래 문제를 풀어보세요.
- 3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용안됨)
- 3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용)
- 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용안됨)
- 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용)


# 09-07

#### Q82.
아래사항을 참조, 파이썬의 heapq 라이브러리를 활용하여 주어진 리스트 iterable = [1,3,5,7,9,2,4,6,8,0]을 힙 정렬하여 출력하세요.
- 최소 힙 : heap 역할을 할 빈 리스트를 선언해주고, heappush 메소드의 매개변수로 해당 리스트와 추가하고자 하는 값을 넣어주면 리스트에 힙 정렬이 되게 원하는 값이 삽입된다.
- 최대 힙 : heapq에서는 최대 힙을 제공하지 않는다. 따라서 부호를 변경하는 방법을 사용해서 최대 힙을 구현한다.
