In [2]:
import pandas as pd
import numpy as np

st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [4]:
# 두 학생의 과목별 점수로 사칙연산 수행

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [5]:
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [9]:
# 배열의 연산
arr = np.arange(12.).reshape(3,4)
print(arr,'\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [10]:
# broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [11]:
# dataframe과 series연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [12]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [13]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [14]:
frame + frame

b     d     e
Utah     0.0   2.0   4.0
Ohio     6.0   8.0  10.0
Texas   12.0  14.0  16.0
Oregon  18.0  20.0  22.0

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다


In [15]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    9.0
d    9.0
e    9.0
dtype: float64

In [17]:
frame.apply(f,axis=1)
frame.apply(f,axis='columns')

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

In [18]:
# 여러 값을 가진 시리즈 반환
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [19]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)

b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

## 과제 : 최대한 복잡한 사용자 함수를 생성한 후 df에 적용하여 결과를 출력하세요.

-  중앙정보처리학원 취업 현황 관리 시스템 
-  계산 : 출석률에 대한 취업률

In [76]:
import warnings
warnings.filterwarnings('ignore')


# 졸업생 관련 데이터 생성
id = np.random.randint(1,1001,size=1000)
f1 = pd.Series(id)

np.random.seed(1)

age = np.random.randint(20,40,size=1000)
fr1 = pd.Series(age)

year = np.random.randint(2015,2023,size=1000)
fr2 = pd.Series(year)

attend = np.random.randint(0,160,size=1000)
fr3 = pd.Series(attend)

course = np.random.randint(1,30,size=1000)
fr4 = pd.Series(course)

job = np.random.randint(2,size=1000)
fr5 = pd.Series(job)



chul = pd.concat([f1,fr1,fr2,fr3,fr4,fr5],axis=1)
chul.rename(columns={0:'id',1:'age',2:'year',3:'attend',4:'course',5:'job'},inplace=True)
chul.head(10)


id  age  year  attend  course  job
0  826   25  2017      58       3    0
1  788   31  2021     115      13    0
2  289   32  2015     142       9    1
3  268   28  2020     104      24    1
4  112   29  2022      77      27    1
5  948   31  2022     140      28    1
6  984   25  2020      11      16    0
7  470   35  2022      79      12    0
8  961   20  2017     110      16    1
9  461   36  2016       6      20    1

In [77]:
# 함수 생성 (1) 분반 기준 현재 출석률(160일 기준)

def attend_rate(x):
    x = x / 160 * 100
    return '%.f'%x

chul['attend rate'] = chul.attend.apply(lambda x:attend_rate(x))
chul.head()

id  age  year  attend  course  job attend rate
0  826   25  2017      58       3    0          36
1  788   31  2021     115      13    0          72
2  289   32  2015     142       9    1          89
3  268   28  2020     104      24    1          65
4  112   29  2022      77      27    1          48

In [79]:
# 함수 생성 (2) course에 대한 카테고리 분류

def get_category1(x):
    course_class = ''
    if x < 10:
        course_class = 'Big data'
    elif x < 20:
        course_class = 'Frontend'
    else :
        course_class = 'Backend'
    
    return course_class
            
chul['course_class'] = chul.course.apply(lambda x:get_category1(x))
chul.head()

id  age  year  attend  course  job attend rate course_class
0  826   25  2017      58       3    0          36     Big data
1  788   31  2021     115      13    0          72     Frontend
2  289   32  2015     142       9    1          89     Big data
3  268   28  2020     104      24    1          65      Backend
4  112   29  2022      77      27    1          48      Backend

In [ ]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)

In [21]:
# format
format = lambda x:'%.2f'%x
frame.applymap(format)

b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [22]:
frame['e'].map(format)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object