# 선형대수

# 데이터와 행렬
```
스칼라 : 숫자 하나만으로 이루어진 데이터
벡터 : 여러 숫자가 특정한 순서대로 모여 있는 것을 의미. 하나의 벡터를 이루는 데이터 수가 n개이면 n## 데이터와 행렬
스칼라 : 숫자 하나만으로 이루어진 데이터
벡터 : 여러 숫자가 특정한 순서대로 모여 있는 것을 의미. 하나의 벡터를 이루는 데이터 수가 n기이면 n-차원 벡터라고 함
열벡터는 열의 수가 1인 행렬
하나의 데이터 레코드를 단독으로 벡터로 나타낼 때는 하나의 열로 나타내고 복수의 데이터 레코드 집합을 행렬로 나타낼 때는 하나의 데이터 레코드가 하나의 행으로 표기하는 것은 데이터 분석에서 일반적인 관례
스칼라와 벡터도 수학적으로는 행렬에 속한다.
스칼라는 열과 행의 수가 각각 1인 행렬이고 벡터는 열의 수가 1인 행렬이다.

Python Numpy 선형대수
단위행렬 (Unit matrix): np.eye(n)
대각행렬 (Diagonal matrix): np.diag(x)
내적 (Dot product, Inner product): np.dot(a, b)
대각합 (Trace): np.trace(x)
행렬식 (Matrix Determinant): np.linalg.det(x)
역행렬 (Inverse of a matrix): np.linalg.inv(x)
고유값 (Eigenvalue), 고유벡터 (Eigenvector): w, v = np.linalg.eig(x)
특이값 분해 (Singular Value Decomposition): u, s, vh = np.linalg.svd(A)
```
https://rfriend.tistory.com/380

In [1]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

벡터 a를 벡터 b와 같은 방향의 성분과 그렇지 않은 성분으로 분해한다고 할 때 의 길이는 벡터 b와 같은 방향의 성분 길이와 같다.

벡터 a와 b의 내적은 벡터 b의 길이와 벡터 a에서 벡터 b와 같은 방향의 성분 길이를 곱한 것이다.

- 행렬 내적은 행렬 곱이며 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능
- 행렬 내적의 특성으로 왼쪽 행렬의 열개수와 오른쪽 행렬의 행개수가 동일해야 내적 연산 가능

In [3]:
# 내적
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [4]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [7]:
x = np.arange(1,7).reshape(2,3)
y = np.array([[6.,23],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [9]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

행렬 곱을 응용하여 신경망에 적용
<img src='./행렬곱.jpg' size=10>